### ISSUE TITLE
Generated Kotlin Code References Non-Existent Message Instead of Outer Class

### ISSUE THREAD

**Issue by akosyakov** [connectrpc/connect-kotlin#378]
**Description**

When using the `buf.build/connectrpc/kotlin` plugin, if a service and a nested message inside a response share the same name (e.g., `MytestService` and `ListMytestsResponse.Mytest`), the generated `ServiceClient` and `ServiceClientInterface` incorrectly reference the nested message type directly instead of using the expected outer class (`MytestOuterClass`). This results in compilation errors because the referenced type does not exist.

**Steps to Reproduce** 
1. Define the following .proto file:

  ```proto
  syntax = "proto3";
  
  package myorg.v1;
  
  service MytestService {
    rpc ListMytests(ListMytestsRequest) returns (ListMytestsResponse) {}
  }
  
  message ListMytestsRequest {}
  
  message ListMytestsResponse {
    message Mytest {}
  
    repeated Mytest tests = 2;
  }
  ```

2. Use the following buf.gen.yaml:

  ```yaml
  version: v1
  plugins:
    - plugin: buf.build/protocolbuffers/java
      out: ../java/src/main/java
    - plugin: buf.build/connectrpc/kotlin
      out: ../java/src/main/java
  ```
  
3. Run Buf code generation.

The generated Kotlin code for `MytestServiceClient` and `MytestServiceClientInterface` references `Mytest`, which does not exist, instead of `MytestOuterClass`.
